# Generated by Django 4.2.25 on 2025-10-07 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(related_name='eventos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
